WITH RECURSIVE TREE AS (
    SELECT
        *, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT
        D.*, (T.GENERATION + 1)
    FROM ECOLI_DATA D
    INNER JOIN TREE T ON T.ID = D.PARENT_ID
)
SELECT
    COUNT(T.ID) COUNT, T.GENERATION
FROM TREE T
WHERE NOT EXISTS (
    SELECT 1 FROM ECOLI_DATA WHERE PARENT_ID = T.ID
)
GROUP BY T.GENERATION
ORDER BY T.GENERATION

